import { z } from "zod";
import { getDailyRanking, oliverStoreConfigured, putDailyRanking, rankingKey, stableHash } from "@/lib/oliver-store";

export const maxDuration=60;
const symbols=["AAPL","MSFT","NVDA","AMZN","META","GOOGL","TSLA"] as const;
const reviewSchema=z.object({symbol:z.enum(symbols),review:z.object({stateClassification:z.string(),locationClassification:z.string(),boxStatus:z.string(),stateQuality:z.number(),locationQuality:z.number(),premarketContextQuality:z.number(),spaceQuality:z.number(),riskQuality:z.number(),overallQuality:z.number(),oliverInterest:z.enum(["Yes","Maybe","No"]),wouldTrade:z.enum(["Yes","Maybe","No"]),direction:z.enum(["Long","Short","None / unclear"]),setupType:z.string(),overallGrade:z.enum(["A+","A","B","C","Reject"]),confidence:z.number(),strongestReason:z.string(),biggestConcern:z.string(),rationale:z.object({overall:z.string()}).passthrough()}).passthrough()});
const requestSchema=z.object({sessionDate:z.string(),timeframe:z.enum(["1m","5m","15m"]),modelVersion:z.string(),reviews:z.array(reviewSchema).length(7),manual:z.boolean().optional().default(false)});
const resultSchema=z.object({bestSymbol:z.enum([...symbols,"NO_TRADE"] as const),secondSymbol:z.enum([...symbols,"NO_TRADE"] as const),noTradeDay:z.boolean(),winnerReason:z.string(),separationReason:z.string(),confidence:z.number().int().min(1).max(5)});
const jsonSchema={type:"object",additionalProperties:false,required:["bestSymbol","secondSymbol","noTradeDay","winnerReason","separationReason","confidence"],properties:{bestSymbol:{type:"string",enum:[...symbols,"NO_TRADE"]},secondSymbol:{type:"string",enum:[...symbols,"NO_TRADE"]},noTradeDay:{type:"boolean"},winnerReason:{type:"string"},separationReason:{type:"string"},confidence:{type:"integer",minimum:1,maximum:5}}} as const;
function outputText(data:any){if(typeof data.output_text==="string")return data.output_text;return(data.output??[]).flatMap((item:any)=>item.content??[]).map((part:any)=>part.text??"").join("")}
export async function POST(request:Request){
 try{
  const parsed=requestSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:"Daily ranking requires seven completed AI reviews."},{status:400});
  const input=parsed.data;const evidence={sessionDate:input.sessionDate,timeframe:input.timeframe,modelVersion:input.modelVersion,reviews:input.reviews};const inputHash=stableHash(evidence);const key=rankingKey({...input,source:"ai"});const cached=await getDailyRanking(key,inputHash);
  if(cached?.ranking)return Response.json({ranking:{...cached.ranking,cached:true},cached:true,storeConfigured:oliverStoreConfigured()});
  if(!input.manual)return Response.json({error:"No saved Nexus daily ranking exists. Run the manual Nexus day review first.",manualRequired:true},{status:409});
  const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)return Response.json({error:"OPENAI_API_KEY is not configured."},{status:503});const model=process.env.OPENAI_TEXT_MODEL||"gpt-5-mini";
  const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model,store:false,instructions:["You are Nexus making the independent daily comparison for Digital Oliver.","All seven reviews are frozen decision-time assessments. Outcome/future information is forbidden.","Choose the best and second-best actionable setup, or NO_TRADE when appropriate.","Weigh State → Location → Structure Box → Space → Power → Risk rather than sorting a single score.","If noTradeDay is true, both symbols must be NO_TRADE."].join("\n"),input:JSON.stringify(evidence),text:{format:{type:"json_schema",name:"digital_oliver_daily_rank",strict:true,schema:jsonSchema}}})});
  if(!response.ok){const detail=await response.text();console.error("Oliver AI daily rank failed",response.status,detail);return Response.json({error:"Nexus could not rank the seven Oliver cases."},{status:502});}
  const data=await response.json();let json:unknown;try{json=JSON.parse(outputText(data))}catch{return Response.json({error:"Nexus returned an unreadable daily ranking."},{status:502})};const rank=resultSchema.safeParse(json);if(!rank.success)return Response.json({error:"Nexus returned an incomplete daily ranking."},{status:502});
  const ranking={...rank.data,generatedAt:new Date().toISOString(),model:data.model||model,modelVersion:input.modelVersion,timeframe:input.timeframe,cached:false};await putDailyRanking({ranking_key:key,session_date:input.sessionDate,timeframe:input.timeframe,model_version:input.modelVersion,source:"ai",input_hash:inputHash,ranking,generated_at:ranking.generatedAt});return Response.json({ranking,cached:false,storeConfigured:oliverStoreConfigured()});
 }catch(error){console.error("Oliver AI daily rank route failed",error);return Response.json({error:"Nexus could not rank the seven Oliver cases."},{status:500})}
}
