"use client";

import { useEffect, useState } from "react";
import type { CaseReview, DigitalOliverWorkspaceState, OliverMarketSnapshot, OliverTab } from "@/lib/digital-oliver";
import { MAG7, OLIVER_RULEBOOK_SUMMARY, selectedCase, updateCase } from "@/lib/digital-oliver";
import OliverMarketChart from "@/components/oliver-market-chart";

type Props = { state: DigitalOliverWorkspaceState; onChange: (next: DigitalOliverWorkspaceState) => void };
const tabs: Array<[OliverTab,string]> = [["guidedReview","Guided Review"],["dailyRanking","Daily Ranking"],["evidenceLibrary","Evidence Library"],["statistics","Statistics"],["export","Export"],["rulebook","Rulebook / Method"]];
const stateOptions=["Narrow","Trending Up","Trending Down","Wide Up","Wide Down","Transitional","Unclear"];
const locationOptions=["Favorable","Neutral / unclear","Unfavorable","Extended","Reclaiming level","Rejecting level"];
const boxOptions=["Inside box","Testing upper edge","Testing lower edge","Broke above","Broke below","Failed breakout","Box unclear"];
const powerOptions=["Bull Elephant","Bear Elephant","Bull 180","Bear 180","Bottoming Tail","Topping Tail","Strong color change","No meaningful power"];

function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="oliver-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Range({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="oliver-field"><span>{label} · {value}/5</span><input type="range" min="1" max="5" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Text({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className="oliver-field"><span>{label}</span>{area?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="oliver-check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function metric(v:unknown,s=""){return v===null||v===undefined||v===""?"—":`${v}${s}`}

export default function DigitalOliverWorkspace({state,onChange}:Props){
 const current=selectedCase(state); const patch=(p:Partial<CaseReview>)=>onChange(updateCase(state,current.caseId,p));
 const locked=state.cases.filter(c=>c.locked).length; const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function loadMarket(refresh=false,signal?:AbortSignal){setLoading(true);setError("");try{const q=new URLSearchParams({symbol:current.symbol,interval:state.selectedTimeframe,fullDay:state.fullDay?"1":"0",refresh:refresh?"1":"0"});if(/^\d{4}-\d{2}-\d{2}$/.test(current.sessionDate))q.set("date",current.sessionDate);const r=await fetch(`/api/oliver_market?${q}`,{signal});const d=await r.json();if(!r.ok)throw new Error(d.error||"Market engine could not load this case.");const snap:OliverMarketSnapshot={...d,loadedAt:new Date().toISOString()};const next=updateCase(state,current.caseId,{caseRef:snap.caseRef,sessionDate:snap.sessionDate});onChange({...next,marketSnapshot:snap,updatedAt:new Date().toISOString()})}catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Market engine failed.")}finally{setLoading(false)}}
 useEffect(()=>{const c=new AbortController();void loadMarket(false,c.signal);return()=>c.abort();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[current.symbol,state.selectedTimeframe,state.fullDay]);
 const snapshot=state.marketSnapshot?.symbol===current.symbol&&state.marketSnapshot.interval===state.selectedTimeframe?state.marketSnapshot:null; const engine=snapshot?.candidate;
 return <section className="oliver-workspace">
  <div className="oliver-titlebar"><div><span className="eyebrow">ACTIVE WORKSPACE</span><h1>Digital Oliver</h1><p>State → Location → Structure Box → Space → Power → Risk → rank → lock → validate</p></div><div className="oliver-progress"><strong>{locked}/{state.cases.length}</strong><span>cases locked</span></div></div>
  <nav className="oliver-tabs">{tabs.map(([k,l])=><button key={k} className={state.activeTab===k?"active":""} onClick={()=>onChange({...state,activeTab:k,updatedAt:new Date().toISOString()})}>{l}</button>)}</nav>
  {state.activeTab==="guidedReview"&&<div className="oliver-review">
   <aside className="oliver-case-rail"><small>CASE QUEUE</small>{state.cases.map(c=><button key={c.caseId} className={c.caseId===current.caseId?"active":""} onClick={()=>onChange({...state,selectedCaseId:c.caseId,marketSnapshot:null})}><strong>{c.symbol}</strong><span>{MAG7[c.symbol]}</span><i>{c.locked?"Locked":c.reviewState.replace("_"," ")}</i></button>)}</aside>
   <div className="oliver-case-main">
    <div className="oliver-case-head"><div><span className="case-ref">{current.caseRef}</span><h2>{current.symbol} · {MAG7[current.symbol]}</h2><p>{current.sessionDate}</p></div><div className="timeframe-group">{(["5m","15m","1m"] as const).map(tf=><button key={tf} className={state.selectedTimeframe===tf?"active":""} onClick={()=>onChange({...state,selectedTimeframe:tf,marketSnapshot:null})}>{tf}</button>)}<button className={state.fullDay?"active":""} onClick={()=>onChange({...state,fullDay:!state.fullDay,marketSnapshot:null})}>Full day</button><button onClick={()=>void loadMarket(true)}>Refresh</button></div></div>
    <div className="oliver-chart-shell">{loading&&<div className="oliver-chart-empty"><strong>Loading real market evidence…</strong><span>Python market-data + Oliver engine</span></div>}{!loading&&error&&<div className="oliver-chart-empty error"><strong>Market engine unavailable</strong><span>{error}</span></div>}{!loading&&!error&&snapshot&&<OliverMarketChart snapshot={snapshot}/>}</div>
    {engine?.has_data&&<div className="engine-evidence"><div><span>Engine score</span><strong>{metric(engine.score)}</strong></div><div><span>Direction</span><strong>{metric(engine.direction)}</strong></div><div><span>State</span><strong>{metric(engine.state)}</strong></div><div><span>Space</span><strong>{metric(engine.space_r,engine.space_r==null?"":"R")}</strong></div><div><span>Structure Box</span><strong>{engine.box_cleared?"Cleared":"Contained / near"}</strong></div><p>{engine.reason}</p></div>}
    <div className="oliver-section"><div className="section-heading"><span>1</span><div><h3>Oliver Rulebook Checklist</h3><p>The marked chart is engine evidence. Your judgment stays separate below.</p></div></div>
     <div className="oliver-grid three"><Select label="State" value={current.stateClassification} options={stateOptions} onChange={v=>patch({stateClassification:v,reviewState:"in_progress"})}/><Select label="Location" value={current.locationClassification} options={locationOptions} onChange={v=>patch({locationClassification:v,reviewState:"in_progress"})}/><Select label="Structure Box" value={current.boxStatus} options={boxOptions} onChange={v=>patch({boxStatus:v,reviewState:"in_progress"})}/></div>
     <div className="oliver-grid three compact"><Range label="State quality" value={current.stateQuality} onChange={v=>patch({stateQuality:v})}/><Range label="Location quality" value={current.locationQuality} onChange={v=>patch({locationQuality:v})}/><Range label="Space quality" value={current.spaceQuality} onChange={v=>patch({spaceQuality:v})}/><Range label="Premarket/open" value={current.premarketContextQuality} onChange={v=>patch({premarketContextQuality:v})}/><Range label="Risk quality" value={current.riskQuality} onChange={v=>patch({riskQuality:v})}/><Range label="Overall quality" value={current.overallQuality} onChange={v=>patch({overallQuality:v})}/></div>
     <div className="oliver-check-grid"><Check label="Clear structure box identified" checked={current.structureBoxRelevant} onChange={v=>patch({structureBoxRelevant:v})}/><Check label="Price cleared the box" checked={current.boxCleared} onChange={v=>patch({boxCleared:v})}/><Check label="Trend aligned" checked={current.trendAlignment} onChange={v=>patch({trendAlignment:v})}/><Check label="Volume confirms" checked={current.volumeConfirmation} onChange={v=>patch({volumeConfirmation:v})}/><Check label="Previous close relevant" checked={current.priorCloseRelevant} onChange={v=>patch({priorCloseRelevant:v})}/><Check label="Previous high/low relevant" checked={current.priorHighLowRelevant} onChange={v=>patch({priorHighLowRelevant:v})}/><Check label="Prior late-day range relevant" checked={current.priorRangeRelevant} onChange={v=>patch({priorRangeRelevant:v})}/><Check label="20 SMA relevant" checked={current.sma20Relevant} onChange={v=>patch({sma20Relevant:v})}/><Check label="200 SMA relevant" checked={current.sma200Relevant} onChange={v=>patch({sma200Relevant:v})}/></div>
     <div className="power-pills">{powerOptions.map(p=>{const a=current.powerTypes.includes(p);return <button key={p} className={a?"active":""} onClick={()=>patch({powerTypes:a?current.powerTypes.filter(x=>x!==p):[...current.powerTypes.filter(x=>x!=="No meaningful power"),p]})}>{p}</button>})}</div>
    </div>
    <div className="oliver-section"><div className="section-heading"><span>2</span><div><h3>Our Oliver Judgment</h3><p>Keep human judgment separate from engine evidence.</p></div></div><div className="oliver-grid three"><Select label="Would Oliver be interested?" value={current.oliverInterest} options={["Unreviewed","Yes","Maybe","No"]} onChange={v=>patch({oliverInterest:v as CaseReview["oliverInterest"]})}/><Select label="Would Oliver actually trade it?" value={current.wouldTrade} options={["Unreviewed","Yes","Maybe","No"]} onChange={v=>patch({wouldTrade:v as CaseReview["wouldTrade"]})}/><Select label="Direction" value={current.direction} options={["Long","Short","None / unclear"]} onChange={v=>patch({direction:v as CaseReview["direction"]})}/><Select label="Setup family" value={current.setupType} options={["Unclassified","Elephant Bar","Bull/Bear 180","Power Tail","Location/State only","No valid setup","Other"]} onChange={v=>patch({setupType:v})}/><Select label="Overall grade" value={current.overallGrade} options={["A+","A","B","C","Reject"]} onChange={v=>patch({overallGrade:v as CaseReview["overallGrade"]})}/><Range label="Confidence" value={current.confidence} onChange={v=>patch({confidence:v})}/></div><Text label="Biggest reason FOR the trade" value={current.strongestReason} onChange={v=>patch({strongestReason:v})}/><Text label="Biggest concern" value={current.biggestConcern} onChange={v=>patch({biggestConcern:v})}/></div>
    <div className="oliver-section"><div className="section-heading"><span>3</span><div><h3>Michael + Nexus Discussion</h3><p>Nexus receives this selected case and Python engine snapshot automatically.</p></div></div><div className="oliver-grid two"><Text area label="Michael's analysis" value={current.michaelAnalysis} onChange={v=>patch({michaelAnalysis:v})}/><Text area label="Nexus / ChatGPT analysis" value={current.chatgptAnalysis} onChange={v=>patch({chatgptAnalysis:v})}/></div><Text area label="Combined conclusion / where we agree or disagree" value={current.combinedConclusion} onChange={v=>patch({combinedConclusion:v})}/><Text label="What did we learn?" value={current.lesson} onChange={v=>patch({lesson:v})}/><div className="lock-row"><Check label="Lock interpretation" checked={current.locked} onChange={v=>patch({locked:v,reviewState:v?"complete":"in_progress"})}/><span>{current.locked&&snapshot?.outcome?`Outcome available: ${metric(snapshot.outcome.mfe_r,"R MFE")} · ${metric(snapshot.outcome.mae_r,"R MAE")}`:"Outcome remains separated until interpretation lock."}</span></div></div>
   </div>
  </div>}
  {state.activeTab==="dailyRanking"&&<div className="oliver-empty"><strong>Daily Ranking migrated structurally</strong><p>All seven interpretations remain required before ranking. The 35-case weekly queue is the next persistence/workflow slice.</p></div>}
  {state.activeTab==="evidenceLibrary"&&<div className="oliver-library">{state.cases.map(c=><div key={c.caseId}><strong>{c.caseRef}</strong><span>{c.symbol} · {c.overallGrade} · {c.oliverInterest}</span><p>{c.combinedConclusion||c.michaelAnalysis||"No saved interpretation yet."}</p></div>)}</div>}
  {state.activeTab==="statistics"&&<div className="oliver-empty"><strong>Statistics connected to the engine boundary</strong><p>Real outcomes are available; aggregate statistics remain gated until durable weekly evidence is migrated.</p></div>}
  {state.activeTab==="export"&&<div className="oliver-empty"><strong>Export workflow preserved</strong><p>Permanent case/week export returns with durable server persistence.</p></div>}
  {state.activeTab==="rulebook"&&<div className="oliver-rulebook"><h2>Digital Oliver Rulebook workflow</h2><p>{OLIVER_RULEBOOK_SUMMARY.purpose}</p><div className="rule-hierarchy">{OLIVER_RULEBOOK_SUMMARY.hierarchy.map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div><h3>Evidence discipline</h3><p>{OLIVER_RULEBOOK_SUMMARY.evidenceDiscipline}</p><h3>Current encoded model scope</h3><ul>{OLIVER_RULEBOOK_SUMMARY.modelScope.encoded.map(x=><li key={x}>{x}</li>)}</ul><h3>Planned model work</h3><ul>{OLIVER_RULEBOOK_SUMMARY.modelScope.planned.map(x=><li key={x}>{x}</li>)}</ul></div>}
 </section>
}
