"use client";

import { useEffect, useMemo, useState } from "react";
import type { CaseReview, DigitalOliverWorkspaceState, OliverMarketSnapshot, OliverModelSettings, OliverTab } from "@/lib/digital-oliver";
import { DEFAULT_MODEL_SETTINGS, MAG7, OLIVER_RULEBOOK_SUMMARY, casesForSelectedDate, ensureCasesForDate, groupSessionsByWeek, selectedCase, updateCase, weekKey } from "@/lib/digital-oliver";
import OliverMarketChart from "@/components/oliver-market-chart";

type Props={state:DigitalOliverWorkspaceState;onChange:(next:DigitalOliverWorkspaceState)=>void};
const tabs:Array<[OliverTab,string]>=[["guidedReview","Guided Review"],["modelSettings","Model Settings"],["dailyRanking","Daily Ranking"],["evidenceLibrary","Evidence Library"],["statistics","Statistics"],["export","Export"],["rulebook","Rulebook / Method"]];
const stateOptions=["Narrow","Trending Up","Trending Down","Wide Up","Wide Down","Transitional","Unclear"];
const locationOptions=["Favorable","Neutral / unclear","Unfavorable","Extended","Reclaiming level","Rejecting level"];
const boxOptions=["Inside box","Testing upper edge","Testing lower edge","Broke above","Broke below","Failed breakout","Box unclear"];
const powerOptions=["Bull Elephant","Bear Elephant","Bull 180","Bear 180","Bottoming Tail","Topping Tail","Strong color change","No meaningful power"];
const symbols=Object.keys(MAG7) as Array<keyof typeof MAG7>;

function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="oliver-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Range({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="oliver-field"><span>{label} · {value}/5</span><input type="range" min="1" max="5" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Text({label,value,onChange,area=false}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean}){return <label className="oliver-field"><span>{label}</span>{area?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="oliver-check"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function metric(v:unknown,s=""){return v===null||v===undefined||v===""?"—":`${v}${s}`}
function fmtDate(date:string){return new Intl.DateTimeFormat("en-US",{weekday:"short",month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`))}
function weekLabel(start:string,dates:string[]){const end=dates[dates.length-1]??start;return `${fmtDate(start).replace(/^[A-Za-z]{3}, /,"")} – ${fmtDate(end).replace(/^[A-Za-z]{3}, /,"")} · ${dates.length} trading day${dates.length===1?"":"s"}`}

function Setting({label,value,min,max,step,unit,help,onChange}:{label:string;value:number;min:number;max:number;step:number;unit?:string;help:string;onChange:(v:number)=>void}){
 return <div className="model-setting"><div><strong>{label}</strong><p>{help}</p></div><div className="setting-control"><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/>{unit&&<span>{unit}</span>}</div></div>
}

export default function DigitalOliverWorkspace({state,onChange}:Props){
 const current=selectedCase(state); const patch=(p:Partial<CaseReview>)=>onChange(updateCase(state,current.caseId,p));
 const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const [settingsDraft,setSettingsDraft]=useState<OliverModelSettings>(state.modelSettings);
 useEffect(()=>setSettingsDraft(state.modelSettings),[state.modelSettings]);
 const weeks=useMemo(()=>groupSessionsByWeek(state.availableSessions),[state.availableSessions]);
 const selectedWeek=state.selectedDate?weekKey(state.selectedDate):(weeks[0]?.[0]??"");
 const selectedWeekDates=weeks.find(([k])=>k===selectedWeek)?.[1]??[];
 const dayCases=casesForSelectedDate(state);
 const locked=dayCases.filter(c=>c.locked).length;
 const weekCaseCount=selectedWeekDates.length*symbols.length;
 const persistedWeekCases=state.cases.filter(c=>selectedWeekDates.includes(c.sessionDate));
 const lockedWeekCases=persistedWeekCases.filter(c=>c.locked).length;

 function querySettings(q:URLSearchParams,s:OliverModelSettings){Object.entries(s).forEach(([k,v])=>{if(k!=="version")q.set(k,String(v))})}
 async function loadMarket(refresh=false,signal?:AbortSignal,dateOverride?:string,symbolOverride?:string){
  setLoading(true);setError("");try{
   const symbol=(symbolOverride??current.symbol) as keyof typeof MAG7; const date=dateOverride??state.selectedDate??current.sessionDate;
   const q=new URLSearchParams({symbol,interval:state.selectedTimeframe,fullDay:state.fullDay?"1":"0",refresh:refresh?"1":"0"});
   if(/^\d{4}-\d{2}-\d{2}$/.test(date))q.set("date",date); querySettings(q,state.modelSettings);
   const r=await fetch(`/api/oliver_market?${q}`,{signal});const d=await r.json();if(!r.ok)throw new Error(d.error||"Market engine could not load this case.");
   const snap:OliverMarketSnapshot={...d,loadedAt:new Date().toISOString()};
   const sessions=Array.from(new Set([...(state.availableSessions??[]),...snap.availableSessions])).sort();
   const activeWeek=weekKey(snap.sessionDate);
   const activeWeekDates=sessions.filter(session=>weekKey(session)===activeWeek);
   let next=state;
   for(const session of activeWeekDates) next=ensureCasesForDate(next,session);
   next=ensureCasesForDate(next,snap.sessionDate);
   const target=next.cases.find(c=>c.sessionDate===snap.sessionDate&&c.symbol===symbol)!;
   next=updateCase(next,target.caseId,{caseRef:snap.caseRef,sessionDate:snap.sessionDate});
   onChange({...next,selectedDate:snap.sessionDate,selectedCaseId:target.caseId,availableSessions:sessions,marketSnapshot:snap,weekId:activeWeek,updatedAt:new Date().toISOString()});
  }catch(e){if(e instanceof DOMException&&e.name==="AbortError")return;setError(e instanceof Error?e.message:"Market engine failed.")}finally{setLoading(false)}
 }

 useEffect(()=>{const c=new AbortController();void loadMarket(false,c.signal);return()=>c.abort();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[current.symbol,state.selectedDate,state.selectedTimeframe,state.fullDay,state.modelSettings.version]);

 function selectDate(date:string){let next=ensureCasesForDate(state,date);const existing=next.cases.find(c=>c.sessionDate===date&&c.symbol===current.symbol)??next.cases.find(c=>c.sessionDate===date)!;onChange({...next,selectedDate:date,selectedCaseId:existing.caseId,marketSnapshot:null,weekId:weekKey(date),updatedAt:new Date().toISOString()});}
 function selectWeek(week:string){const dates=weeks.find(([k])=>k===week)?.[1]??[];if(!dates.length)return;let next=state;for(const date of dates)next=ensureCasesForDate(next,date);const preferred=dates.includes(state.selectedDate)?state.selectedDate:dates[dates.length-1];const target=next.cases.find(c=>c.sessionDate===preferred&&c.symbol===current.symbol)??next.cases.find(c=>c.sessionDate===preferred)!;onChange({...next,weekId:week,selectedDate:preferred,selectedCaseId:target.caseId,marketSnapshot:null,updatedAt:new Date().toISOString()});}
 function selectSymbol(symbol:keyof typeof MAG7){let next=ensureCasesForDate(state,state.selectedDate);const target=next.cases.find(c=>c.sessionDate===state.selectedDate&&c.symbol===symbol)!;onChange({...next,selectedCaseId:target.caseId,marketSnapshot:null,updatedAt:new Date().toISOString()});}
 function applySettings(){const nextVersion=`Oliver v${(Number((state.modelSettings.version.match(/v(\d+(?:\.\d+)?)/)?.[1]??"0.1"))+0.1).toFixed(1)}`;onChange({...state,modelSettings:{...settingsDraft,version:nextVersion},marketSnapshot:null,updatedAt:new Date().toISOString()});}
 function resetSettings(){setSettingsDraft({...DEFAULT_MODEL_SETTINGS});}
 const snapshot=state.marketSnapshot?.symbol===current.symbol&&state.marketSnapshot.interval===state.selectedTimeframe&&state.marketSnapshot.sessionDate===state.selectedDate?state.marketSnapshot:null; const engine=snapshot?.candidate;

 return <section className="oliver-workspace">
  <div className="oliver-titlebar"><div><span className="eyebrow">ACTIVE WORKSPACE</span><h1>Digital Oliver</h1><p>State → Location → Structure Box → Space → Power → Risk → rank → lock → validate</p><div className="migration-feature-badges"><span>Week/day navigation active</span><span>Global model settings active</span><span>{state.modelSettings.version}</span></div></div><div className="oliver-progress"><strong>{locked}/{dayCases.length}</strong><span>cases locked today</span></div></div>
  <nav className="oliver-tabs">{tabs.map(([k,l])=><button key={k} className={state.activeTab===k?"active":""} onClick={()=>onChange({...state,activeTab:k,updatedAt:new Date().toISOString()})}>{l}</button>)}</nav>

  {state.activeTab==="guidedReview"&&<>
   <div className="date-navigator">
    <label><span>Research week</span><select value={selectedWeek} onChange={e=>selectWeek(e.target.value)} disabled={!weeks.length}>{weeks.length?weeks.map(([k,dates])=><option key={k} value={k}>{weekLabel(k,dates)}</option>):<option value="">Loading trading calendar…</option>}</select></label>
    <div className="day-buttons">{selectedWeekDates.map(d=><button key={d} className={state.selectedDate===d?"active":""} onClick={()=>selectDate(d)}><strong>{new Intl.DateTimeFormat("en-US",{weekday:"short",timeZone:"UTC"}).format(new Date(`${d}T12:00:00Z`))}</strong><span>{d.slice(5)}</span></button>)}</div>
    <div className="date-step"><button disabled={!state.availableSessions.length||state.availableSessions.indexOf(state.selectedDate)<=0} onClick={()=>{const i=state.availableSessions.indexOf(state.selectedDate);if(i>0)selectDate(state.availableSessions[i-1])}}>← Previous trading day</button><button disabled={!state.availableSessions.length||state.availableSessions.indexOf(state.selectedDate)>=state.availableSessions.length-1} onClick={()=>{const i=state.availableSessions.indexOf(state.selectedDate);if(i>=0&&i<state.availableSessions.length-1)selectDate(state.availableSessions[i+1])}}>Next trading day →</button></div>
    <div className="week-case-summary"><strong>{selectedWeekDates.length} days · {weekCaseCount} cases</strong><span>{lockedWeekCases} locked · 7 symbols per day</span></div>
   </div>
   <div className="oliver-review">
    <aside className="oliver-case-rail"><small>{state.selectedDate?fmtDate(state.selectedDate):"CASE QUEUE"}</small>{symbols.map(symbol=>{const c=state.cases.find(x=>x.sessionDate===state.selectedDate&&x.symbol===symbol);return <button key={symbol} className={current.symbol===symbol?"active":""} onClick={()=>selectSymbol(symbol)}><strong>{symbol}</strong><span>{MAG7[symbol]}</span><i>{c?.locked?"Locked":c?.reviewState?.replace("_"," ")??"unreviewed"}</i></button>})}</aside>
    <div className="oliver-case-main">
     <div className="oliver-case-head"><div><span className="case-ref">{current.caseRef}</span><h2>{current.symbol} · {MAG7[current.symbol]}</h2><p>{state.selectedDate?fmtDate(state.selectedDate):current.sessionDate}</p></div><div className="timeframe-group">{(["5m","15m","1m"] as const).map(tf=><button key={tf} className={state.selectedTimeframe===tf?"active":""} onClick={()=>onChange({...state,selectedTimeframe:tf,marketSnapshot:null,updatedAt:new Date().toISOString()})}>{tf}</button>)}<button className={state.fullDay?"active":""} onClick={()=>onChange({...state,fullDay:!state.fullDay,marketSnapshot:null,updatedAt:new Date().toISOString()})}>Full day</button><button onClick={()=>void loadMarket(true)}>Refresh</button></div></div>
     <div className="oliver-chart-shell">{loading&&<div className="oliver-chart-empty"><strong>Loading market evidence…</strong><span>Python Oliver engine · {state.modelSettings.version}</span></div>}{!loading&&error&&<div className="oliver-chart-empty error"><strong>Market engine unavailable</strong><span>{error}</span></div>}{!loading&&!error&&snapshot&&<OliverMarketChart snapshot={snapshot}/>}</div>
     {engine?.has_data&&<div className="engine-evidence"><div><span>Engine score</span><strong>{metric(engine.score)}</strong></div><div><span>Direction</span><strong>{metric(engine.direction)}</strong></div><div><span>State</span><strong>{metric(engine.state)}</strong></div><div><span>Space</span><strong>{metric(engine.space_r,engine.space_r==null?"":"R")}</strong></div><div><span>Structure Box</span><strong>{engine.box_cleared?"Cleared":"Contained / near"}</strong></div><p>{engine.reason}</p></div>}
     <div className="oliver-section"><div className="section-heading"><span>1</span><div><h3>Oliver Rulebook Checklist</h3><p>The marked chart is engine evidence. Your judgment stays separate below.</p></div></div><div className="oliver-grid three"><Select label="State" value={current.stateClassification} options={stateOptions} onChange={v=>patch({stateClassification:v,reviewState:"in_progress"})}/><Select label="Location" value={current.locationClassification} options={locationOptions} onChange={v=>patch({locationClassification:v,reviewState:"in_progress"})}/><Select label="Structure Box" value={current.boxStatus} options={boxOptions} onChange={v=>patch({boxStatus:v,reviewState:"in_progress"})}/></div><div className="oliver-grid three compact"><Range label="State quality" value={current.stateQuality} onChange={v=>patch({stateQuality:v})}/><Range label="Location quality" value={current.locationQuality} onChange={v=>patch({locationQuality:v})}/><Range label="Space quality" value={current.spaceQuality} onChange={v=>patch({spaceQuality:v})}/><Range label="Premarket/open" value={current.premarketContextQuality} onChange={v=>patch({premarketContextQuality:v})}/><Range label="Risk quality" value={current.riskQuality} onChange={v=>patch({riskQuality:v})}/><Range label="Overall quality" value={current.overallQuality} onChange={v=>patch({overallQuality:v})}/></div><div className="oliver-check-grid"><Check label="Clear structure box identified" checked={current.structureBoxRelevant} onChange={v=>patch({structureBoxRelevant:v})}/><Check label="Price cleared the box" checked={current.boxCleared} onChange={v=>patch({boxCleared:v})}/><Check label="Trend aligned" checked={current.trendAlignment} onChange={v=>patch({trendAlignment:v})}/><Check label="Volume confirms" checked={current.volumeConfirmation} onChange={v=>patch({volumeConfirmation:v})}/><Check label="Previous close relevant" checked={current.priorCloseRelevant} onChange={v=>patch({priorCloseRelevant:v})}/><Check label="Previous high/low relevant" checked={current.priorHighLowRelevant} onChange={v=>patch({priorHighLowRelevant:v})}/><Check label="Prior late-day range relevant" checked={current.priorRangeRelevant} onChange={v=>patch({priorRangeRelevant:v})}/><Check label="20 SMA relevant" checked={current.sma20Relevant} onChange={v=>patch({sma20Relevant:v})}/><Check label="200 SMA relevant" checked={current.sma200Relevant} onChange={v=>patch({sma200Relevant:v})}/></div><div className="power-pills">{powerOptions.map(p=>{const a=current.powerTypes.includes(p);return <button key={p} className={a?"active":""} onClick={()=>patch({powerTypes:a?current.powerTypes.filter(x=>x!==p):[...current.powerTypes.filter(x=>x!=="No meaningful power"),p]})}>{p}</button>})}</div></div>
     <div className="oliver-section"><div className="section-heading"><span>2</span><div><h3>Our Oliver Judgment</h3><p>Keep human judgment separate from engine evidence.</p></div></div><div className="oliver-grid three"><Select label="Would Oliver be interested?" value={current.oliverInterest} options={["Unreviewed","Yes","Maybe","No"]} onChange={v=>patch({oliverInterest:v as CaseReview["oliverInterest"]})}/><Select label="Would Oliver actually trade it?" value={current.wouldTrade} options={["Unreviewed","Yes","Maybe","No"]} onChange={v=>patch({wouldTrade:v as CaseReview["wouldTrade"]})}/><Select label="Direction" value={current.direction} options={["Long","Short","None / unclear"]} onChange={v=>patch({direction:v as CaseReview["direction"]})}/><Select label="Setup family" value={current.setupType} options={["Unclassified","Elephant Bar","Bull/Bear 180","Power Tail","Location/State only","No valid setup","Other"]} onChange={v=>patch({setupType:v})}/><Select label="Overall grade" value={current.overallGrade} options={["A+","A","B","C","Reject"]} onChange={v=>patch({overallGrade:v as CaseReview["overallGrade"]})}/><Range label="Confidence" value={current.confidence} onChange={v=>patch({confidence:v})}/></div><Text label="Biggest reason FOR the trade" value={current.strongestReason} onChange={v=>patch({strongestReason:v})}/><Text label="Biggest concern" value={current.biggestConcern} onChange={v=>patch({biggestConcern:v})}/></div>
     <div className="oliver-section"><div className="section-heading"><span>3</span><div><h3>Michael + Nexus Discussion</h3><p>Nexus receives this exact date, symbol, review, and engine snapshot.</p></div></div><div className="oliver-grid two"><Text area label="Michael's analysis" value={current.michaelAnalysis} onChange={v=>patch({michaelAnalysis:v})}/><Text area label="Nexus / ChatGPT analysis" value={current.chatgptAnalysis} onChange={v=>patch({chatgptAnalysis:v})}/></div><Text area label="Combined conclusion" value={current.combinedConclusion} onChange={v=>patch({combinedConclusion:v})}/><Text label="What did we learn?" value={current.lesson} onChange={v=>patch({lesson:v})}/><div className="lock-row"><Check label="Lock interpretation" checked={current.locked} onChange={v=>patch({locked:v,reviewState:v?"complete":"in_progress"})}/><span>{current.locked&&snapshot?.outcome?`Outcome available: ${metric(snapshot.outcome.mfe_r,"R MFE")} · ${metric(snapshot.outcome.mae_r,"R MAE")}`:"Outcome remains separated until interpretation lock."}</span></div></div>
    </div>
   </div>
  </>}

  {state.activeTab==="modelSettings"&&<div className="model-settings-page"><div className="settings-head"><div><span className="eyebrow">GLOBAL MODEL DEFINITIONS</span><h2>{state.modelSettings.version}</h2><p>These values define how every Digital Oliver chart is evaluated. Change a value once, save it, and every subsequently viewed chart is recalculated with that definition set.</p></div><div><button onClick={resetSettings}>Reset defaults</button><button className="primary" onClick={applySettings}>Save settings globally</button></div></div>
   <section><h3>State</h3><Setting label="Fast SMA" value={settingsDraft.fastSma} min={5} max={100} step={1} unit="bars" help="Fast moving average used in market-state classification." onChange={v=>setSettingsDraft({...settingsDraft,fastSma:v})}/><Setting label="Slow SMA" value={settingsDraft.slowSma} min={50} max={300} step={1} unit="bars" help="Slow moving average used with the fast SMA to define broad state." onChange={v=>setSettingsDraft({...settingsDraft,slowSma:v})}/><Setting label="Narrow separation" value={settingsDraft.narrowSepAtr} min={0.1} max={2} step={0.05} unit="ATR" help="Maximum fast/slow separation that can qualify as Narrow." onChange={v=>setSettingsDraft({...settingsDraft,narrowSepAtr:v})}/><Setting label="Wide separation" value={settingsDraft.wideSepAtr} min={0.5} max={5} step={0.1} unit="ATR" help="Minimum fast/slow separation that qualifies as Wide." onChange={v=>setSettingsDraft({...settingsDraft,wideSepAtr:v})}/><Setting label="Trend slope threshold" value={settingsDraft.trendSlopeAtr} min={0.01} max={0.5} step={0.01} unit="ATR/bar" help="Minimum normalized fast-SMA slope used to classify trending states." onChange={v=>setSettingsDraft({...settingsDraft,trendSlopeAtr:v})}/><Setting label="Slope lookback" value={settingsDraft.slopeLookback} min={2} max={20} step={1} unit="bars" help="Number of bars used to estimate fast-SMA slope." onChange={v=>setSettingsDraft({...settingsDraft,slopeLookback:v})}/></section>
   <section><h3>Location & Structure Box</h3><Setting label="Location distance" value={settingsDraft.locationAtr} min={0.1} max={2} step={0.05} unit="ATR" help="How close price must be to a moving average to count as near location." onChange={v=>setSettingsDraft({...settingsDraft,locationAtr:v})}/><Setting label="Structure Box lookback" value={settingsDraft.structureLookback} min={3} max={30} step={1} unit="bars" help="Prior bars used to construct every rolling Structure Box. Set this to 6 and save to make all charts use a six-bar box." onChange={v=>setSettingsDraft({...settingsDraft,structureLookback:v})}/><Setting label="Minimum Space" value={settingsDraft.minSpaceR} min={0.5} max={5} step={0.1} unit="R" help="Minimum room to the nearest known obstacle considered acceptable." onChange={v=>setSettingsDraft({...settingsDraft,minSpaceR:v})}/></section>
   <section><h3>Elephant / Power Definition</h3><Setting label="Range lookback" value={settingsDraft.elephantLookback} min={5} max={50} step={1} unit="bars" help="Prior bars used to establish normal candle range." onChange={v=>setSettingsDraft({...settingsDraft,elephantLookback:v})}/><Setting label="Minimum range multiple" value={settingsDraft.elephantRangeMult} min={1} max={3} step={0.05} unit="×" help="Elephant candle range must exceed normal range by at least this multiple." onChange={v=>setSettingsDraft({...settingsDraft,elephantRangeMult:v})}/><Setting label="Minimum body ratio" value={settingsDraft.elephantBodyRatio} min={0.4} max={0.95} step={0.01} unit="of range" help="Minimum fraction of total candle range occupied by the body." onChange={v=>setSettingsDraft({...settingsDraft,elephantBodyRatio:v})}/><Setting label="Strong close threshold" value={settingsDraft.elephantStrongClose} min={0.5} max={0.98} step={0.01} unit="of range" help="How close to the directional extreme an Elephant must close." onChange={v=>setSettingsDraft({...settingsDraft,elephantStrongClose:v})}/><Setting label="Max opposite wick" value={settingsDraft.elephantMaxOppositeWick} min={0.02} max={0.5} step={0.01} unit="of range" help="Maximum wick allowed against the Elephant direction." onChange={v=>setSettingsDraft({...settingsDraft,elephantMaxOppositeWick:v})}/></section>
   <section><h3>Risk & Session Context</h3><Setting label="ATR length" value={settingsDraft.atrLen} min={5} max={50} step={1} unit="bars" help="ATR period used for normalized state, location and structure measurements." onChange={v=>setSettingsDraft({...settingsDraft,atrLen:v})}/><Setting label="Opening candidate window" value={settingsDraft.openingWindowMinutes} min={15} max={180} step={5} unit="minutes" help="How long after the open the engine searches for its primary candidate." onChange={v=>setSettingsDraft({...settingsDraft,openingWindowMinutes:v})}/><Setting label="Premarket start" value={settingsDraft.premarketStartHour} min={4} max={8} step={1} unit=":00 ET" help="Beginning of the premarket window used for reference levels." onChange={v=>setSettingsDraft({...settingsDraft,premarketStartHour:v})}/></section>
  </div>}

  {state.activeTab==="dailyRanking"&&<div className="oliver-empty"><strong>Daily Ranking</strong><p>The selected trading day contains seven symbol cases. Lock all seven interpretations before ranking that day.</p></div>}
  {state.activeTab==="evidenceLibrary"&&<div className="oliver-library">{state.cases.filter(c=>/^\d{4}-\d{2}-\d{2}$/.test(c.sessionDate)).sort((a,b)=>b.sessionDate.localeCompare(a.sessionDate)).map(c=><div key={c.caseId}><strong>{c.caseRef}</strong><span>{fmtDate(c.sessionDate)} · {c.symbol} · {c.overallGrade} · {c.oliverInterest}</span><p>{c.combinedConclusion||c.michaelAnalysis||"No saved interpretation yet."}</p></div>)}</div>}
  {state.activeTab==="statistics"&&<div className="oliver-empty"><strong>Statistics connected to dated evidence</strong><p>Aggregate comparison by week and model version is the next persistence step.</p></div>}
  {state.activeTab==="export"&&<div className="oliver-empty"><strong>Export workflow preserved</strong><p>Permanent historical export will move to durable server storage.</p></div>}
  {state.activeTab==="rulebook"&&<div className="oliver-rulebook"><h2>Digital Oliver Rulebook workflow</h2><p>{OLIVER_RULEBOOK_SUMMARY.purpose}</p><div className="rule-hierarchy">{OLIVER_RULEBOOK_SUMMARY.hierarchy.map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div><h3>Current global version</h3><p>{state.modelSettings.version}</p><h3>Evidence discipline</h3><p>{OLIVER_RULEBOOK_SUMMARY.evidenceDiscipline}</p><h3>Current encoded model scope</h3><ul>{OLIVER_RULEBOOK_SUMMARY.modelScope.encoded.map(x=><li key={x}>{x}</li>)}</ul></div>}
 </section>
}
